### ISSUE TITLE
Great job! But why use this dank wallet to create a canister, and spending 12 TC cycles?

### ISSUE THREAD

**Issue by flyq** [Psychedelic/dank#16]
```sh
dfx wallet --network ic balance
63000000000000 cycles.
```

here is the principal `yhy6j-huy54-mkzda-m26hc-yklb3-dzz4l-i2ykq-kr7tx-dhxyf-v2c2g-tae`

**Comment by kanej** [comment]
Hey @flyq, canisters require cycles to perform compute and storage. When they are created some cycles are used to create the canister, but an additional amount of cycles are transferred to the created canister as a supply for future compute and storage (which can be topped up later if required). By default `dfx` puts 4TC into a newly created canister for this purpose.

We expect the cost of creating a canister to be similar whether you use `personal cycle wallet` or `xtc`. Roughly 4TC per canister deployed. 12TC is unexpected.

Can you confirm that it was one canister that was deployed?
Can you share the `dfx.json` from the project deployed?

Thanks

**Comment by kanej** [comment]
Hey @flyq, I am going to close this issue, but can re-open if you have more questions.
